name: API test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt

    - name: Python test
      id: check-result-python
      run: |
        if python3 test/test.py -d test/generated_stub/; then
          echo 'PASSED PYTHON test'
        else
          echo 'FAILED PYTHON test'
          exit 1
        fi

    - name: C++ test
      id: check-result-test
      run: |
        cd test
        g++ test.cpp -o test -I ../gendc_cpp/gendc_separator/
        if ./test; then
          echo 'PASSED C++ test'
        else
          echo 'FAILED C++ test'
          exit 1
        fi