name: Release GenDC Header Library

on:
  push:
    tags:
      - 'v*'  # triggered by tag starting with 'v'

jobs:
  release-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create ZIP Archive
      run: |
        cd gendc_cpp
        cp ../LICENSE.txt .
        zip -r gendc_separator_${{ github.ref_name }}_win64.zip gendc_separator

    - name: Update gendc-python version by tag
      run: |
        new_version=${{ github.ref_name }}
        echo "
        __version__ = '${new_version:1}' # this was automatically updated by cicd at release
        from . import gendc_separator
        " > ${{ github.workspace }}/gendc_python/__init__.py

    - name: Save version tag
      run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Commit updates
      uses: EndBug/add-and-commit@v7
      with:
        branch: main
        message: "Update gendc-pyton module version to ${{ github.ref_name }} by Release workflow"
        add: "['${{ github.workspace }}/gendc_python/__init__.py']"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
              gendc_cpp/gendc_separator*.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish python module
      uses: ./.github/workflows/python-publish.yml
      with:
        refname: ${{ github.ref_name }}